
<article class="container plot_context">
	<div class="plot_content container col-sm-12">
		<h2>Plot</h2>
		<p>The series begins with the execution of Gol D. Roger, a man known as the King of the Pirates (ŠC‘¯‰¤ Kaizoku??). Just before his death, Roger announces that his treasure, the One Piece (‚Ð‚Æ‚Â‚È‚¬‚Ì‘å”é•ó (ƒƒ“ƒs[ƒX) Wan P?su?), will be available to anyone who finds it, beginning the Great Pirate Era (‘åŠC‘¯Žž‘ã Daikaizokujidai?). As a result, countless pirates set out to the Grand Line to look for the treasure. </br>

Twenty-two years have passed since Roger's execution, and Monkey D. Luffy, a young man inspired by his childhood idol and powerful pirate "Red Haired" Shanks, sets off on a journey from the East Blue sea to find the One Piece and proclaim himself as the King of the Pirates. In an effort to organize his own crew, the Straw Hat Pirates (”ž‚í‚çŠC‘¯’c•Ñ Mugiwara Kaizoku-dan?), Luffy rescues and befriends a swordsman named Roronoa Zoro, and they head off in search of the One Piece. They are joined by Nami, a navigator and thief; Usopp, a sniper and a liar; and Sanji, a womanizing chef; in their journey, they acquire a ship named the Going Merry and engage in confrontations with pirates including Buggy the Clown, Captain Kuro and Don Krieg. Later, Luffy encounters Arlong, a fishman and member of the former Sun Pirates who thinks that fishmen are superior to humans. After Luffy defeats Arlong, Nami officially joins Luffy's crew and the Navy places a bounty on Luffy's head. Luffy, then meets Captain Smoker, a Navy captain who can turn into smoke. He briefly captures Luffy, but Luffy is saved by his father, Monkey D. Dragon, who is identified by Smoker simply as Dragon, the most wanted man in the world. After making their way into the Grand Line, the group meets Nefeltari Vivi, a princess who wants to help save her country, the Alabasta Kingdom, from the crime syndicate Baroque Works. They later befriend the doctor and anthropomorphized reindeer Tony Tony Chopper while in Drum Island.</br>

The Straw Hat Pirates arrive in Alabasta, leading to battles with Baroque Works and their leader, Sir Crocodile. Luffy finally defeats Crocodile and liberates Alabasta. Soon after, Nico Robin, an archaeologist formerly employed by Baroque Works, joins Luffy's crew. They soon encounter Blackbeard, the alias of Marshall D. Teech, who also aspires to become the King of the Pirates. After traveling to the flying island of Skypiea, the crew gets involved in a war between the Skypieans and the Shandorians, leading to a confrontation against the island's ruler, Eneru, who has the power of lightning. Luffy defeats Eneru to save Skypiea and end the war. The crew soon meets the navy admiral Aokiji, who reveals that Robin was involved in searching for Poneglyphs, which are stones with markings left by an ancient civilization to reveal the missing 100 years of history that the World Government had erased. The group goes to Water 7, where they battle the cyborg shipwright Franky and are informed that the Going Merry is damaged beyond repair, leading to Usopp's temporary departure from the Straw Hat Pirates. However, Cipher Pol No. 9, the World Government's intelligence agency, captures Robin and Franky for information regarding the Poneglyphs and the ancient weapons that may come from them. Franky liberates himself from the government after burning his blueprints for one of the weapons, Pluton, and teams up with the Straw Hat Pirates to declare war on the government, resulting in battles between CP9 and its members. The final long battle with CP9 ends when the crew saves Robin. To replace the sunken Going Merry, Franky constructs a new ship, the Thousand Sunny, for the Straw Hats and officially joins the crew. Soon after, the crew helps a musician skeleton named Brook, who was revived after eating a Devil Fruit, find his shadow aboard the gigantic pirate ship Thriller Bark, which has been stolen by Gecko Moriah. After defeating Moriah, Brook joins Luffy's crew.</br>

After arriving at Saboady Archipelago, the crew prepares to sail to the New World, the second half of Grand Line. While there, they befriend Silvers Rayleigh, the vice captain of Roger's pirate crew who they ask to coat their ship so they can travel underwater. The crew eventually gets separated during a battle with Bartholomew Kuma, a huge cyborg under the control of the Navy, at the Sabaody Archipelago; Luffy is transported to the all-female island Amazon Lily. Having learned that his adoptive older brother and the son of Gol D. Roger, Portgas D. Ace, has been detained at the government prison Impel Down, Luffy traverses there and liberates several of its prisoners, including the fish man Jimbei and some former enemies. However, Luffy soon learns that Ace is at Marineford to be executed at Navy headquarters. As Luffy arrives, war breaks out between the Navy and a group of pirates led by the legendary pirate Edward Newgate, also known by the alias Whitebeard. In the ensuing chaos, Whitebeard and Ace are killed. At Rayleigh's request, Luffy has his crewmates undergo rigorous training regimens, some under the tutelage of prominent figures.</br>

Two years later, the crew regroups at Sabaody Archipelago and journeys to Fishman Island to enter the New World. During this time, a group of fishman pirates appear, seeking supremacy against humans, and hold a coup d'etat to decide the fate of the island. However, after Nami forgives Jimbei for releasing Arlong into the East Blue, the Straw Hats defeat the fishmen pirates, saving the island. The Straw Hats leave Fishman Island and finally reach the New World, though not before starting a feud with Charlotte "Big Mom" Linlin, one of the "Four Emperors", the strongest pirates in the New World. Entering the half-burning and half-freezing island Punk Hazard, the crew encounters an old acquaintance and a recently appointed Warlord, Trafalgar Law, and they form an alliance to take down Kaido, another of the Four Emperors. The alliance is drawn into a fierce battle against Caesar Clown, the scientist responsible for the destruction of Punk Hazard four years earlier, who is in the service of Donquixote Doflamingo. After Caesar's defeat, the alliance travels to Dressrosa, a kingdom ruled by Donquixote Doflamingo in an attempt to destroy the Smile factory as the next phase to defeat one of the Four Emperors, Kaido. In Dressrosa, Luffy competes in a competition to receive the Flame-Flame Fruit, formerly used by Ace. Sanji, Nami, Brook, and Chopper leave Dressrosa when Big Mom arrives to attack the Thousand Sunny. Luffy's other adoptive brother, Sabo, arrives and assumes Luffy's place in the competition to earn the Flame-Flame Fruit as Luffy leaves to rescue his friends. Luffy and Trafalgar Law defeat Doflamingo in a battle for Dressrosa's fate and save the country however, they have to flee Dressrosa from naval forces led by Admiral Fujitora to regroup with the others. After escaping a pirate alliance made-up of Doflamingo's underworld clients, the leaders of seven crews form an alliance that swear their loyalty to Luffy and create the Straw Hat Grand Fleet. Luffy, the remaining Straw Hats, Law, and two samurai know head to the mysterious island of Zou, which is on top of a giant elephant, in search for the remaining Straw Hats, the Heart Pirates and Momonosuke, a son of one of the samurai.<p>
<h3>To be continue...</h3>
	</div>
</article>
